---
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: "info"
  logs:
    custom_components.tuyahombli: "debug"
  filters:
    homeassistant.components.go2rtc:
      - "Could not find go2rtc docker binary"
    homeassistant.setup:
      - ".*go2rtc.*"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
